version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    image: nginx:1.0
    depends_on:
       - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes: 
      - ./requirements/nginx/conf:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl
      - wp-volume:/var/www/
    restart: unless-stopped
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
    container_name: mariadb
    image: mariadb:1.0
    networks:
      - inception
    volumes: 
      - db-volume:/var/lib/mysql
    restart: unless-stopped
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
    container_name: wordpress
    image: wordpress:1.0
    networks: 
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes: 
      - wp-volume:/var/www/
  
volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
        
networks:
  inception:
    driver: bridge
