version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
       - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes: 
      - ./requirements/nginx/conf:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl
    restart: always
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args: 
        DB_NAME: wordpress
        DB_USER: segarcia
        DB_PASS: password
        DB_ROOT: root_password
    container_name: mariadb
    ports:
       - "3306:3306"
    networks:
      - inception
    restart: always
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
          DB_NAME: wordpress
          DB_USER: segarcia
          DB_PASS: password
    container_name: wordpress
    networks: 
      - inception
    depends_on:
      - mariadb
    restart: always
  
networks:
  inception:
